[package]
name = "kuzu-ogm-macros"
version = "0.1.0"
edition = "2021"
description = "Proc macros for kuzu-ogm"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
serde_json = "1.0" 